
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Build container and Helm
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
  - task: Docker@0
    displayName: Build an image
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'DockeHub'
      action: 'Build an image'
      dockerFile: '**/Dockerfile'
      imageName: 'nefilime/devops4fun:$(Build.BuildId)'
  - task: Docker@0
    displayName: Push an image
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'DockeHub'
      action: 'Push an image'
      imageName: 'nefilime/devops4fun:$(Build.BuildId)'
    
  - task: SSH@0
    displayName: deploy to ECS instance
    inputs:
      sshEndpoint: 'Ali'
      runOptions: 'commands'
      commands: |
        docker stop sat
        docker rm sat
        docker run -d -p 80:80 --name sat nefilime/devops4fun:$(Build.BuildId)
      readyTimeout: '20000'

  


  