
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Build container and Helm
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
  - task: Docker@0
    displayName: Build an image
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'DockeHub'
      action: 'Build an image'
      dockerFile: '**/Dockerfile'
      imageName: 'nefilime/devops4fun:$(Build.BuildId)'
  - task: Docker@0
    displayName: Push an image
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'DockeHub'
      action: 'Push an image'
      imageName: 'nefilime/devops4fun:$(Build.BuildId)'
  - task: HelmDeploy@0
    displayName: helm package
    inputs:
      namespace: devopsfun-$(Build.BuildId)
      command: package
      chartPath: Helm/
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Helm Package'
    inputs:
      ArtifactName: Helm Package
  