apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: {{ .Release.Name }}-devopsfun
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: akscluster.eastus2.cloudapp.azure.com
    http:
      paths:
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: devopsfun-service
            port:
              number: 80
