apiVersion: v1
kind: Service
metadata:
  name: devopsfun-service
  namespace: {{ .Release.Name }}-devopsfun
spec:
  selector:
    app: {{ .Release.Name }}-devopsfun
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
