name:  trigger Azure pipeline

on:
  pull_request:
    branches: main
    types: closed
   
   
jobs:
    build:
        name: Call Azure Pipeline
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: hhttps://dev.azure.com/6074442/CI-03
            azure-pipeline-name: 'Nefilime.devops4fun'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
